name: Publish NuGet Packages

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets.csproj
          dotnet restore Hexa.NET.ImGui.Widgets.Extras/Hexa.NET.ImGui.Widgets.Extras.csproj

      - name: Build the project
        run: |
          dotnet build Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets.csproj --configuration Release
          dotnet build Hexa.NET.ImGui.Widgets.Extras/Hexa.NET.ImGui.Widgets.Extras.csproj --configuration Release

      - name: Pack the project
        run: |
          dotnet pack Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets.csproj --configuration Release --output ./nupkgs
          dotnet pack Hexa.NET.ImGui.Widgets.Extras/Hexa.NET.ImGui.Widgets.Extras.csproj --configuration Release --output ./nupkgs

      - name: Exclude unwanted packages
        run: |
          for package in ./nupkgs/*.nupkg; do
              package_name=$(basename "$package")
              if [[ ! $package_name == Hexa.NET* ]]; then
                  echo "Removing $package_name as it does not start with Hexa.NET."
                  rm -f "$package"
              fi
          done
          
      - name: List packages
        run: ls ./nupkgs/

      - name: Publish the package
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
